### ISSUE TITLE
storage_invest example does not work for a fixed storage

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof_base#27]
If you switch the investment option to _False_ the example raises an error.

```diff
- transformer.Storage.optimization_options.update({'investment': True})
+ transformer.Storage.optimization_options.update({'investment': False})

storage = transformer.Storage(uid='sto_simple',
                              inputs=[bel],
                              outputs=[bel],
                              eta_in=1,
                              eta_out=0.8,
                              cap_loss=0.00,
                              opex_fix=35,
                              opex_var=10e10,
                              capex=1000,
-                             cap_max=0,
+                             cap_max=1000,
                              cap_initial=0,
                              c_rate_in=1/6,
                              c_rate_out=1/6)
```
```python
Traceback (most recent call last):
  File "/home/uwe/rli-lokal/git_home/oemof_base/examples/storage_optimization/storage_invest.py", line 155, in <module>
    energysystem.optimize()
  File "/home/uwe/rli-lokal/git_home/oemof_base/oemof/core/energy_system.py", line 89, in optimize
    self.optimization_model = OM(energysystem=self)
  File "/home/uwe/rli-lokal/git_home/oemof_base/oemof/solph/optimization_model.py", line 114, in __init__
    assembler.registry[cls](e=None, om=self, block=block)
  File "/home/uwe/rli-lokal/git_home/oemof_base/oemof/solph/optimization_model.py", line 551, in _
    om.default_assembler(block)
  File "/home/uwe/rli-lokal/git_home/oemof_base/oemof/solph/optimization_model.py", line 162, in default_assembler
    block.optimization_options[option](self, block)
  File "/home/uwe/rli-lokal/git_home/oemof_base/oemof/solph/optimization_model.py", line 532, in linear_constraints
    var.set_bounds(om, block, side='output')
  File "/home/uwe/rli-lokal/git_home/oemof_base/oemof/solph/variables.py", line 144, in set_bounds
    model.w[e1, e2, t].setub(out_max[e1][0])
TypeError: 'NoneType' object is not subscriptable
```

**Comment by simonhilpert** [comment]
I think you will need to set out_max, and in_max as list (the max. power for charging and discharging)
usually i should be calculated automatically, if not set in the __init__ of transformers.Storage() class. 
for you: 
```python
out_max = [1/6*1000]
in_max = [1/6*1000]
```

**Comment by simonhilpert** [comment]
I fixed it in the dev branch.

**Comment by uvchik** [comment]
That's smart. Thank you
